//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryPunchList.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Punchlist
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Punchlist()
        {
            this.Updates = new HashSet<Update>();
        }
    
        public int id { get; set; }
        public Nullable<int> Assignee { get; set; }
        public Nullable<int> Type { get; set; }
        public string Description { get; set; }
        public string Location { get; set; }
        public string Image { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
    
        public virtual Supervisor Supervisor { get; set; }
        public virtual Type Type1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Update> Updates { get; set; }
    }
}
